# Generated by Django 2.2.1 on 2019-05-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0002_auto_20190505_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commit',
        ),
    ]
