# Generated by Django 2.2.1 on 2019-05-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0003_delete_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
