# Generated by Django 2.2.1 on 2019-05-14 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0007_auto_20190508_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256, unique=True)),
                ('url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_integration.Repository')),
            ],
        ),
    ]
