# Generated by Django 2.2.1 on 2019-05-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0009_auto_20190514_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='sha',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
